In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('olympics.csv',  sep=',', encoding='latin-1')
df

,pais,jogos_verao,ouro,prata,bronze,total_verao,jogos_inverno,ouro_1,prata_1,bronze_1,total_inverno,total_olimpiadas,total_ouro,total_prata,total_bronze,total_geral
0,AFG Afeganistão,14,0,0,2,2,0,0,0,0,0,14,0,0,2,2
1,RSA África do Sul,20,27,33,29,89,7,0,0,0,0,27,27,33,29,89
2,GER Alemanha[3][4],17,201,205,246,652,12,92,88,60,240,29,293,293,306,892
3,GDR Alemanha Oriental[5],5,153,129,127,409,6,39,36,35,110,11,192,165,162,519
4,FRG Alemanha Ocidental[3][5],5,56,67,81,204,7,11,15,13,39,12,67,82,94,243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,ZAM Zâmbia,14,0,1,1,2,0,0,0,0,0,14,0,1,1,2
152,ZIM Zimbabwe,14,3,4,1,8,1,0,0,0,0,15,3,4,1,8
153,ZZX Equipa mista[31],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
154,IOA Atletas Olímpicos Independentes[IOA],3,1,0,1,2,0,0,0,0,0,3,1,0,1,2
155,IOP Participantes Olímpicos Independentes[IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3